In [2]:
import numpy as np
from scipy import signal
import matplotlib.pyplot as plt
# import tkinter
import my_utilities as mu
from spike_manipulator import Spikes

# Controls
ei          = 3                     # electrode index
norm_spks   = 1                     # normalize spikes? 0='no', 1='yes'
fnums       = [4, 7, 11, 8]         # file number to load
# fnums       = [1, 3]              # file number to load
norm_len    = 199                   # normalized spike lengths
stim_mode   = "all"                 # stimulus edge used to keep neural signals = "rise", "fall", or "all"
save_dat    = 1

# Constants
dat_dir     = 'Data/Raw/'           # directory where .mat neural data files are located
sig_colors  = ['g', 'b', 'y', 'r', 'm']

# main
num_files = len(fnums)
X_good = []
X = []
y = []

for fnum in fnums:
    raw, fname = mu.load_raw(dat_dir, fnum, 0)
    spks = Spikes(raw, stim_mode, 0)
    spks_good = spks.to_good_spikes(ei)
    spks_norm = spks.normalize(spks_good, norm_len)
    # spks_norm = spks_good[:100,:]
    spks_len = spks.spks_len
    n_spks = spks.num_good_spks

    ones_arr = np.ones(n_spks).astype('int')
    labels = mu.get_label(fname) * ones_arr

    if fnum == fnums[0]:
        X_good = np.array(spks_good)
        X = np.array(spks_norm)
        y = labels
    else:
        X_good = np.append(X_good, spks_good, axis=1)
        X = np.append(X, spks_norm, axis=1)
        y = np.append(y, labels)
    
    print(f'{fname} has {n_spks} good spikes with length of {spks_len}')

print(X.shape)
print(y.shape)

# plotting
lb_indexes = y==0
rb_indexes = y==1

# plot spikes (not normalized)
plt.figure()
plt.plot(X_good[:, lb_indexes][:, 0], 'b', label='Left bound')
plt.plot(X_good[:, rb_indexes][:, 0], 'r', label='Right bound')

plt.plot(X_good[:, lb_indexes][:, 1:], 'b')
plt.plot(X_good[:, rb_indexes][:, 1:], 'r')

plt.legend(loc='lower right')
plt.title(f'Full Spikes for Electrode {ei} for {fnums}')

# plot normalized spikes
plt.figure()
plt.plot(X[:, lb_indexes][:, 0], 'b', label='Left bound')
plt.plot(X[:, rb_indexes][:, 0], 'r', label='Right bound')

plt.plot(X[:, lb_indexes][:, 1:], 'b')
plt.plot(X[:, rb_indexes][:, 1:], 'r')

plt.legend(loc='lower right')
plt.title(f'Normalized Spikes for Electrode {ei} for {fnums}')


plt.figure()
plt.plot(y[lb_indexes], '.')

# # plotting
# plt.figure()
# plt.plot(X, 'k')
# plt.title(f'Electrode {ei} for {fnums}')
# plt.figure()
# plt.plot(y, '.')

if save_dat:
    X = X.T
    np.save('XX2', X)
    np.save('yy2', y)
    np.save('zz2', [[], X.shape[0], X.shape[1]])



ImportError: libX11.so.6: cannot open shared object file: No such file or directory

In [72]:
print(X.shape)
print(y.shape)
print(X)
print(y)


(1042, 199)
(1042,)
[[ 0.10141431  0.09580046  0.09018661 ... -0.02847821 -0.02847821
  -0.02847821]
 [-0.02091009 -0.02887729 -0.0368445  ... -0.05918321 -0.05918321
  -0.05918321]
 [ 0.07717978  0.07389504  0.07061029 ...  0.02765844  0.02765844
   0.02765844]
 ...
 [ 0.46459765  0.4553485   0.44609936 ...  0.09930752  0.09930752
   0.09930752]
 [ 0.33823331  0.32808763  0.31794195 ... -0.09632369 -0.09632369
  -0.09632369]
 [ 0.42061223  0.40888812  0.39716401 ...  0.04773288  0.04773288
   0.04773288]]
[1 1 1 ... 0 0 0]


In [73]:
[[], X.shape[0], X.shape[1]]

[[], 1042, 199]

In [74]:
X[0]

array([ 0.10141431,  0.09580046,  0.09018661,  0.08165657,  0.07239747,
        0.06609854,  0.06177306,  0.06345715,  0.07415561,  0.08746691,
        0.11122961,  0.13499231,  0.15896515,  0.18293799,  0.19940571,
        0.21399715,  0.22092446,  0.22274235,  0.22081338,  0.2132641 ,
        0.20521851,  0.19518762,  0.18515673,  0.1781453 ,  0.17113386,
        0.16648716,  0.16243163,  0.15791303,  0.15308571,  0.14870418,
        0.14499135,  0.14248091,  0.14478007,  0.14707922,  0.15362213,
        0.16016504,  0.16532927,  0.17014884,  0.1717088 ,  0.17109571,
        0.16915012,  0.16520578,  0.1618109 ,  0.16061385,  0.1594168 ,
        0.16153616,  0.16365553,  0.16350221,  0.16278073,  0.15913234,
        0.15353268,  0.14783352,  0.14198511,  0.13526176,  0.12503868,
        0.1148156 ,  0.09038793,  0.06596027,  0.02984153, -0.00919999,
       -0.05197245, -0.09723223, -0.14254317, -0.18793086, -0.23347891,
       -0.27966835, -0.32585779, -0.37490485, -0.4239519 , -0.47

In [75]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
a[0]

array([1, 2, 3])

In [77]:
z = y==1
# print(z)
print(X[z])

[[ 0.10141431  0.09580046  0.09018661 ... -0.02847821 -0.02847821
  -0.02847821]
 [-0.02091009 -0.02887729 -0.0368445  ... -0.05918321 -0.05918321
  -0.05918321]
 [ 0.07717978  0.07389504  0.07061029 ...  0.02765844  0.02765844
   0.02765844]
 ...
 [ 0.04723888  0.03638202  0.02552516 ... -0.00089758 -0.00089758
  -0.00089758]
 [ 0.05100848  0.04645712  0.04190577 ...  0.08401661  0.08401661
   0.08401661]
 [ 0.06796991  0.07046407  0.07295824 ...  0.06594861  0.06594861
   0.06594861]]
